### PR TITLE
Add config schema, and use config data properly.

### PR DESCRIPTION
**Pull request by mrstegeman**
Also, remove backwards compatibility with API 1, as it's not
needed.

### CODE REVIEW

**Comment by rzr** [comment]
LGTM I will check it before merging let's target 0.4.1 ?

**Comment by mrstegeman** [comment]
We can merge it as soon as you're done testing, we don't have to wait for an 0.4.1 release. After you cut a new release with these changes, I'll get it pulled into the add-on list. I'd like to wait until then, as there's no clear way to configure the add-on otherwise.

**Comment by rzr** [comment]
Yes I got it, I wanted to make sure It will work with the published images...

I'll test it anyway

Meanwhile, can those 2 be merged for current release  0.0.1 ?

https://github.com/mozilla-iot/addon-list/pull/54
https://github.com/mozilla-iot/gateway/pull/886

**Comment by mrstegeman** [comment]
mozilla-iot/gateway#886 is up to @dhylands

For mozilla-iot/addon-list#54, no, I'd rather have this PR merged first. We don't want to make users configure things on the command line, but without this PR, that's what they'd have to do.

**Comment by rzr** [comment]
OK will try to test this ASAP.

Actually there is no need to use CLI because unless configured using CLI by default all sensors will be available (even if devices not present)...

Like in "mozilla-iot-gateway-sensors-20180406rzr" demo only GPIO where previously configured using CLI.

https://discourse.mozilla.org/t/creating-i2c-add-on/26696/4

**Pull request merged**
