### PR TITLE
Update package.sh for new addon-builder architecture.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Review by rzr — APPROVED** [review]
i will release a version today

**Comment by rzr** [comment]
v0.0.11 has been released should I update the git module ?

**Comment by mrstegeman** [comment]
No need, I'll run the builder.

**Comment by mrstegeman** [comment]
https://github.com/mozilla-iot/addon-list/pull/733

This drops the `linux-ia32` package, for now. I'm happy to add it back and add an i386 builder target if we can actually get a gateway package/image built for something (in an automated way).

**Pull request merged**
