### PR TITLE
Add cross-compile release workflow.

### PR DESCRIPTION
**Pull request by mrstegeman**
When you push a new tag named vX.Y.Z, this will automatically
cross-compile the add-on for all of the supported platforms. This
will allow the release to be handled automatically, rather than
building things manually via WebThingsIO/addon-builder.

### CODE REVIEW

**Comment by rzr** [comment]
great I will try this soon or later

**Comment by mrstegeman** [comment]
Sooner would be preferable, if possible. I'm working on moving all of our existing add-on packages off of S3 before Mozilla shuts it down. In the interim, you could move the packages from S3 to your existing release and we can just update the URLs in the addon-list entry.

**Comment by rzr** [comment]
I just pushed: 

https://github.com/rzr/generic-sensors-webthings/releases/tag/v0.0.14

but didn't try on device

I hope it's fine

**Comment by mrstegeman** [comment]
Hmm, it looks like the workflow didn’t trigger for some reason.

**Pull request merged**
